version = 5.6.0
archive_dir = /etc/letsencrypt/archive/iinstasave.uz
cert = /etc/letsencrypt/live/iinstasave.uz/cert.pem
privkey = /etc/letsencrypt/live/iinstasave.uz/privkey.pem
chain = /etc/letsencrypt/live/iinstasave.uz/chain.pem
fullchain = /etc/letsencrypt/live/iinstasave.uz/fullchain.pem
[renewalparams]
account = 159f77c49e7704e5b9698bcbe2735fea
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
